version: '3'
services:
  database: 
    image: "influxdb"
    ports:
      - "8083:8083"
      - "8086:8086"
  dashboard: 
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    depends_on: 
      - "database"
    volumes: 
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources